In [31]:
import numpy as np
import pandas
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
from sklearn.model_selection import train_test_split 
spams=pandas.read_table("SMSSpamCollection.txt",sep="\t",header=0)
spamsTrain,spamsTest=train_test_split(spams,train_size=0.7,random_state=1)
from sklearn.feature_extraction.text import CountVectorizer
parseur=CountVectorizer()
Xtrain=parseur.fit_transform(spamsTrain['message'])
mdtTrain=Xtrain.toarray()


In [36]:
spams

classe                                            message
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham               Will ü b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [33]:
print(mdtTrain.shape)
print(spamsTrain['classe'].shape)

(3900, 7155)
(3900,)


In [35]:
from sklearn.linear_model import LogisticRegression
modelFirst=LogisticRegression()
modelFirst.fit(mdtTrain,spamsTrain['classe'])
score1=modelFirst.score(mdtTrain,spamsTrain['classe'])
print("score sur data train :"+str(score1))
mdtTest=parseur.transform(spamsTest['message'])
score2=modelFirst.score(mdtTest,spamsTest['classe'])
print("score sur data test :"+str(score2))


score sur data train :0.9976923076923077
score sur data test :0.9814593301435407


In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
     'This is the first document.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?',
 ]
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)

print(vectorizer.vocabulary_)
print(vectorizer.get_feature_names())
print(X.toarray())

{'this': 8, 'is': 3, 'the': 6, 'first': 2, 'document': 1, 'second': 5, 'and': 0, 'third': 7, 'one': 4}
['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
[[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]
 [0.         0.6876236  0.         0.28108867 0.         0.53864762
  0.28108867 0.         0.28108867]
 [0.51184851 0.         0.         0.26710379 0.51184851 0.
  0.26710379 0.51184851 0.26710379]
 [0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]


In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
corpus = [
     'This is the first document.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?',
 ]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.vocabulary_)
print(vectorizer.get_feature_names())
print(X.toarray())

{'this': 8, 'is': 3, 'the': 6, 'first': 2, 'document': 1, 'second': 5, 'and': 0, 'third': 7, 'one': 4}
['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import MultiLabelBinarizer
corpus = [
     'This is the first document.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?',
 ]
vectorizer =  MultiLabelBinarizer()
X = vectorizer.fit(corpus)
X1 = vectorizer.transform(corpus)

print(vectorizer.classes_)
print(X1)

[' ' '.' '?' 'A' 'I' 'T' 'c' 'd' 'e' 'f' 'h' 'i' 'm' 'n' 'o' 'r' 's' 't'
 'u']
[[1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 0 0 0 1 1 1 1 0 1 1 1 1 1 0 1 1 1]
 [1 1 0 1 0 0 0 1 1 0 1 1 0 1 1 1 1 1 0]
 [1 0 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1]]
